travis:
  secure:
    BINSTAR_TOKEN: bYO1V/ljxCdl39OGZuEr+BzSFyERpTBozdMMHq5ErEixILw2J+xeCMBbQcQxn93ZeQm1yyjzoUaT8lnEXGG8B/RIMLEKOQo/5VUZv+iIOPRZWUSIXymm+Ci3Up+PyQFZSjBe32Ota7tQm2DNvEhoIVvG3kOwtOVVhAE3GWIw6MESnnov64rYhIcm+4jVVUGv4K1BBCQc2XelCG8OTkQt2u1djgr7GoN7Y/1RDLi8Py9qktBQ5/40GC5qhTXuyqknm4RRFgZ5Ouj1+wB2LU+dpiHR3oWPIb+2vZGsLJr/stWf1F8S8JYilssd/F/I4Xpcc2URiXgxq2zKeVDK9Lm9SaRxq9IOtvcw3h7WxRmzSonNZS1BSUP7fD4IjdJbQLkvAhj+tAgaTP12TM161tkA1yi2KaaL1g4GDpQnQex8LTuc+loFO5N/B00eM6GXhGQTb042p2yJm6mbKHgfEVU6D1LT8Ps0cT6g50FnQMEVHEO6YoaSseTKhoSiMz+PYWJ4b2Swzn/734RAi1iHq8Y1tsbDTiXrJyfW6WEffOR8HpAi1+WPJNs56KFpoYrAeCSkyBDyoelg/2/3r3pTWY88d+2Cu22uTx9N7TOVN11pbe1AYJ59H7NR5+zqs6S09PYKZ0YoCmp2PucXC8TF1q/LNr41pDQNXl2DfzWNcPRih9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
